[package]
name = "fretboard-trainer"
version = "0.1.0"
authors = ["Eshref Yozdemir <eshrefyoz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
rustfft = "6.0"
csv = "1.1"
serde = { version = "1", features = ["derive"]}

[dependencies.cpal]
version = "0.13.3"
features = ["jack"]
