name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: System Dependencies
      run: sudo apt-get install libasound2-dev libjack-dev libjack0 fontconfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
